# Site settings
name: Fei Li
description: "Msc. in Data Science and Business Analytics, Bocconi University"
url: "https://franli.github.io"

github_username:  franli
# facebook_username: your_facebook_username_goes_here
linkedin_username: francisli100
stack_of_username: 324369/fei-li
email: fei.li@studbocconi.it
# public_key_url: "https://raw.pastebin.com/LINK-TO-PUBLIC-KEY"


avatar: yes
avatar_img_path: "imgs/avatar.jpg"

front_img: yes
# front_img_path: ["imgs/turin3.jpg", "imgs/turin2.jpg", "imgs/beach.jpg"]
front_img_path: "imgs/turin3.jpg"
#front_img_path: "https://external.url/image.jpg"


favicon_img: yes
favicon_img_path: "imgs/favicon.ico"
#favicon_img_path: "https://external.url/favicon.ico"


# Build settings
markdown: kramdown
permalink: pretty

# Dynamic typing
dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
lines: # You can add HTML Tags in the Text
  - text: "条条大路通罗马。"
  - text: "All roads lead to Rome."
  - text: "人生的价值在于奉献。"
  - text: "The value of life lies in what you contribute to others."
  - text: "金无足赤，人无完人。"
  - text: "No one is perfect."
  # - text: ""
  # - text: ""
  # - text: ""